### ISSUE TITLE
RabbitMQ listener port not open

### ISSUE THREAD

**Issue by clepoittevin** [adamamaiga/docker-canopsis#1]
Hello,

With your current configuration, the RabbitMQ listener port is not exposed , so only the admin interface is reachable

The fix is very simple : Change the Run command 

`docker run -d --name canopsis -p 8082:8082 -p 15672:15672 adamamaiga/docker-canopsis`

to

`docker run -d --name canopsis -p 5672:5672 -p 8082:8082 -p 15672:15672 adamamaiga/docker-canopsis`

**Comment by adamamaiga** [comment]
Thank you for your contribution
